services:
  db:
    image: postgres:latest
    container_name: bbventure_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bbventure_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
        
  mailcatcher:
    image: dockage/mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"