CREATE SCHEMA IF NOT EXISTS public;

-- AspNetRoles
CREATE TABLE "AspNetRoles"
(
    "Id"               text NOT NULL
        CONSTRAINT "PK_AspNetRoles"
            PRIMARY KEY,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text
);

ALTER TABLE "AspNetRoles"
    OWNER TO postgres;

CREATE UNIQUE INDEX "RoleNameIndex"
    ON "AspNetRoles" ("NormalizedName");

-- AspNetUsers
CREATE TABLE "AspNetUsers"
(
    "Id"                   text    NOT NULL
        CONSTRAINT "PK_AspNetUsers"
            PRIMARY KEY,
    "UserName"             varchar(256),
    "NormalizedUserName"   varchar(256),
    "Email"                varchar(256),
    "NormalizedEmail"      varchar(256),
    "EmailConfirmed"       boolean NOT NULL,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled"     boolean NOT NULL,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean NOT NULL,
    "AccessFailedCount"    integer NOT NULL
);

ALTER TABLE "AspNetUsers"
    OWNER TO postgres;

CREATE INDEX "EmailIndex"
    ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex"
    ON "AspNetUsers" ("NormalizedUserName");

-- AspNetRoleClaims
CREATE TABLE "AspNetRoleClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_AspNetRoleClaims"
            PRIMARY KEY,
    "RoleId"     text NOT NULL
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
            REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    "ClaimType"  text,
    "ClaimValue" text
);

ALTER TABLE "AspNetRoleClaims"
    OWNER TO postgres;

CREATE INDEX "IX_AspNetRoleClaims_RoleId"
    ON "AspNetRoleClaims" ("RoleId");

-- AspNetUserClaims
CREATE TABLE "AspNetUserClaims"
(
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "PK_AspNetUserClaims"
            PRIMARY KEY,
    "UserId"     text NOT NULL
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "ClaimType"  text,
    "ClaimValue" text
);

ALTER TABLE "AspNetUserClaims"
    OWNER TO postgres;

CREATE INDEX "IX_AspNetUserClaims_UserId"
    ON "AspNetUserClaims" ("UserId");

-- AspNetUserLogins
CREATE TABLE "AspNetUserLogins"
(
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text,
    "UserId"              text NOT NULL
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    CONSTRAINT "PK_AspNetUserLogins"
        PRIMARY KEY ("LoginProvider", "ProviderKey")
);

ALTER TABLE "AspNetUserLogins"
    OWNER TO postgres;

CREATE INDEX "IX_AspNetUserLogins_UserId"
    ON "AspNetUserLogins" ("UserId");

-- AspNetUserRoles
CREATE TABLE "AspNetUserRoles"
(
    "UserId" text NOT NULL
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "RoleId" text NOT NULL
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
            REFERENCES "AspNetRoles"
            ON DELETE CASCADE,
    CONSTRAINT "PK_AspNetUserRoles"
        PRIMARY KEY ("UserId", "RoleId")
);

ALTER TABLE "AspNetUserRoles"
    OWNER TO postgres;

CREATE INDEX "IX_AspNetUserRoles_RoleId"
    ON "AspNetUserRoles" ("RoleId");

-- AspNetUserTokens
CREATE TABLE "AspNetUserTokens"
(
    "UserId"        text NOT NULL
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
            REFERENCES "AspNetUsers"
            ON DELETE CASCADE,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    CONSTRAINT "PK_AspNetUserTokens"
        PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

ALTER TABLE "AspNetUserTokens"
    OWNER TO postgres;

-- Players
CREATE TABLE "Players"
(
    "UserId"        text    NOT NULL
        CONSTRAINT "PK_Players"
            PRIMARY KEY,
    "IsActive"      boolean NOT NULL,
    "Balance"       decimal NOT NULL,
    "CreatedAt"     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt"     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_Players_AspNetUsers_UserId"
        FOREIGN KEY ("UserId")
            REFERENCES "AspNetUsers" ("Id")
            ON DELETE CASCADE
);

ALTER TABLE "Players"
    OWNER TO postgres;

-- Games
CREATE TABLE "Games"
(
    "Id"            uuid NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT "PK_Games"
            PRIMARY KEY,
    "CreatedAt"     timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "EndedAt"       timestamp with time zone,
    "WinnerNumbers" text[],
    "TotalRevenue"  decimal NOT NULL
);

ALTER TABLE "Games"
    OWNER TO postgres;

-- Boards
CREATE TABLE "Boards"
(
    "Id"          uuid NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT "PK_Boards"
            PRIMARY KEY,
    "PlayerId"    text    NOT NULL
        CONSTRAINT "FK_Boards_Players_PlayerId"
            REFERENCES "Players" ("UserId")
            ON DELETE CASCADE,
    "GameId"      uuid    NOT NULL
        CONSTRAINT "FK_Boards_Games_GameId"
            REFERENCES "Games"
            ON DELETE CASCADE,
    "Numbers"     text[],
    "IsAutoplay"  boolean NOT NULL,
    "CreatedAt"   timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt"   timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Boards"
    OWNER TO postgres;

-- Transactions
CREATE TABLE "Transactions"
(
    "Id"                    uuid NOT NULL DEFAULT gen_random_uuid()
        CONSTRAINT "PK_Transactions"
            PRIMARY KEY,
    "PlayerId"              text    NOT NULL
        CONSTRAINT "FK_Transactions_Players_PlayerId"
            REFERENCES "Players" ("UserId")
            ON DELETE CASCADE,
    "Amount"                decimal NOT NULL,
    "CreatedAt"             timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "MobilePayTransactionNumber" text
);

ALTER TABLE "Transactions"
    OWNER TO postgres;
